### ISSUE TITLE
Can't connect to mongodb with username and password

### ISSUE THREAD

**Issue by ghost** [zodern/meteor-up#1001]
I've been searching for an answer to this for ages, I've also posted a question on StackOverflow and the meteor forum. To date, no one can answer me. I don't know if this is a bug or I'm just not understanding something. 

I'm trying to connect my app to MongoDB using `MONGO_URL:`. The database is on an independent VPS. The VPS is behind a firewall and is connected to the app VPS via a private network. If I don't secure the database with a username and password I can get it to connect however if I create a user to allow readWrite commands to add security to the databse it won't connect. I get this error.

`MongoError: failed to connect to server [private-network-ip:27017]`

```
------------------------------------STDERR------------------------------------
	       Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 172.17.0.2 port 80: Connection refused
	  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	                                 Dload  Upload   Total   Spent    Left  Speed
```

If I log into the database and use `show dbs` this is what appears:

    admin         0.000GB
    myspecial_db  0.000GB
    local         0.000GB

I'm trying to connect to `myspecial_db`. 

```
env: {
      ROOT_URL: 'https://myapp.com',
      MONGO_URL: 'mongodb://username:password@private-network-ip:27017/myspecial_db'
    },
```

What am I missing here?

**Comment by SimonSimCity** [comment]
My suggestion: Go on the server via ssh, install `mongodb-clients` and try to connect via the mongodb client using a command like `mongo private-network-ip:27017/myspecial_db -u username -p password`

Just in case you're using some special characters in your username or password, you might have to escape them. It might seem obvious, but I also had the case where my username should contain an `@` sign which blew the show because the rest of the username, including the password, suddenly became part of the domain 😜 

It would also be nice if you'd link your issues at stackoverflow and meteor-forum here ...

**Comment by ghost** [comment]
Thanks for this. The problem turned out to be with my initial setup of the server. All good now. Thanks for the help
