### ISSUE TITLE
Speeding up `Prepare bundle` by extracting the app into the container

### ISSUE THREAD

**Issue by SimonSimCity** [zodern/meteor-up#1002]
I've wondered why a process of deployment takes so much time - specially at the step `Prepare Bundle`. When deploying my app, there's quite some time spent on this and if I run a deploy adding `--verbose`, I see that the `COPY` command of the following section takes quite some time:

https://github.com/zodern/meteor-up/blob/3c7120a75c12ea12fdd5688e33574c12e158fd07/src/plugins/meteor/assets/prepare-bundle.sh#L39-L45

The files copied here are the files which previously are extracted of the zip file which contains my app:

https://github.com/zodern/meteor-up/blob/3c7120a75c12ea12fdd5688e33574c12e158fd07/src/plugins/meteor/assets/prepare-bundle.sh#L26-L29

Just the idea here:

I found this tip (https://nickjanetakis.com/blog/docker-tip-2-the-difference-between-copy-and-add-in-a-dockerile) on a website that we could use `ADD` instead of `COPY` in order to extract the archive into docker. I personally haven't tried it yet but I think it would certainly speed up the process here.

Do you know about this? If yes, have you chosen not to do it for a reason?

**Comment by zodern** [comment]
Thanks for looking into this.

In the `bundle.tar.gz`, the app's files are inside of a `bundle` folder, which results in the files being extracted to the wrong position when using `ADD`.

I experimented with both approaches to compare their performance. I removed the `npm install` command from the docker file. Without that, building the image with `COPY` took 20 - 22 seconds for a 12mb bundle. With `ADD` it took ~9 seconds.  To remove the `bundle` folder, the prepare-bundle script extracted the bundle and recompressed it, which added ~ 2 seconds. The build context was 13.15MB instead of 71.17MB.

One problem with `ADD` is it didn't use cache when the bundle didn't change. With `COPY`, it would use a cached image and only take 5 - 8 seconds and skip running `npm install`.

I plan to add caching for the app's npm dependencies, so they will only need to be installed and rebuilt when the Meteor version changes or the dependencies change. If the files needed for this are copied first with `COPY`, and everything else is added with `ADD`, then `ADD` not using cache wouldn't be as important.

**Comment by SimonSimCity** [comment]
Thanks for clarification. 

As all of this happens on the remote server side, how often does it happen that you are _deploying_ the exact same version to a server, so a docker-image can re-use these layers? In my case it turns out that I never want this. When calling `deploy`, I most of the time either have a broken build (due to network-failures during the previous build) or want to release a new version, so a caching of `npm install` wouldn't really help me since the bundle itself always is different.

But let me try to write down the following as a PR:

1. Extracting sorely the `package.json` and ~`package-lock.json`~ `npm-shrinkwrap.json` from the `bundle.tar.gz` file and copy it into the VM using `COPY`.
1. Install the package dependencies (which might be the same as the previous version which then allows reusing the layers for copying and installing the npm packages).
1. Copy the rest of the app using `ADD`.
1. Move or symlink the folder `node_modules` into the extracted project files.

I guess this comes closest to the last paragraph you wrote, right?

**Comment by SimonSimCity** [comment]
I now spent some time on it and I came up with this:

1. Create the tar containing all the data inside the bundle-folder, but not the folder itself
1. Run the following commands on the server after receiving the bundle:
```bash
gunzip bundle.tar.gz
tar -xvf bundle.tar programs/server/npm-rebuild.js programs/server/npm-shrinkwrap.json programs/server/package.json
```

3. Use this docker file as a template
```docker
FROM abernix/meteord:node-8-base

# Creating a temporary folder
RUN mkdir /npm_packages || true
# Upload the npm-files. The `COPY` sorely checks on the file-content, not on the files metadata, as `ADD` does.
COPY ./programs/server /npm_packages
# Install the npm dependencies and remove the folder again. Now they should be in the npm-cache.
RUN cd  /npm_packages && \
    METEOR_SKIP_NPM_REBUILD=1 npm install --unsafe-perm && \
    cd / && rm -R /npm_packages

# Now we can use the add-command, which will invalidate the docker-cache if the file changed (even only it's meta-data, like the created-at date)
ADD bundle.tar /built_app

# Get the npm packages, which by now should be in the npm-cache.
RUN cd /built_app/programs/server && \
    npm install --unsafe-perm
```

This way would work, but looks quite hacky to me ...

Another solution, I just came across, is shown in the repository https://github.com/shaunwarman/docker-npm-cache where the user just creates a mount for `/root/.npm` on the host. I the downside of this is that the npm-cache will get quite big over time and I don't have an idea to clean it up.

Since you're cleaning up the old docker-images, I'd still prefer my first option over my second one.

https://github.com/zodern/meteor-up/blob/3c7120a75c12ea12fdd5688e33574c12e158fd07/src/plugins/meteor/assets/prepare-bundle.sh#L63

What are your ideas on this?

**Comment by zodern** [comment]
This is a good start.

Meteor's npm dependencies install fairly quickly. The slow part is rebuilding native dependencies, which is what we want to cache.

There are some things that need to be adjusted for compatibility:

1) The current behavior mimics what `meteor build` does. Due to various reasons, some users build the bundle themselves with `meteor build` and then deploy with `mup deploy --cached-build`. I would like to continue to allow that. Maybe we could move the files one level up in the `RUN` command after `ADD`.

2) and 3.
You will also need to copy from `programs/server`
```
# Needed for the rebuild script
npm-rebuild-args.js
npm-rebuilds.json
npm
```

`npm` contains all of the app's and meteor package's npm dependencies, so it can be large. If copying this removes the speed benefit of `ADD`, we can look into only copying the dependencies that need to be rebuilt.

`METEOR_SKIP_NPM_REBUILD=1` shouldn't be set since it only works when the app was deployed from a computer with the exact same architecture.

Thanks for being willing to work on this. I appreciate it.

**Comment by SimonSimCity** [comment]
But out of what you say now, my approach doesn't help much. `METEOR_SKIP_NPM_REBUILD=1` was added because I wanted to skip running the content of `npm-rebuild.js`, of which you now say that this is the most time-consuming. But going this way, it would not even help to cache the `/root/.npm` folder, but I'd rather mount `/built_app/programs/server/node_packages`.

When taking the idea of mounting the `/built_app/programs/server/node_packages` folder, we could add the files via `ADD`, then mount the folder to the correct location and run `npm purge && npm install`. This would skip a rebuild, remove all the unnecessary packages and fetch the updated/new ones, or is there something I forgot?

The question remaining to me is: How does npm handle it if the versions, required by the `npm-shrinkwrap.json` file are not in the cache but in the `node_packages` folder. If it doesn't re-download these packages, this method will work.

Another question popping up now is, if `npm purge && npm install` takes less time than what we saved on replacing `COPY` by `ADD`. At least in my case it would help a lot because I have tons of small files in my meteor-application.

**Comment by zodern** [comment]
In the `programs/server` folder, there is:

- `package.json` this only has a few dependencies needed for the code that boots the node server. These, of course, are installed in the `node_modules` folder.
- `npm/node_modules` These are all of the app's and meteor package's npm dependencies. They are already installed, but the native dependencies were built on the computer the app was deployed from, so they need to be rebuilt. There isn't a `package.json` listing these dependencies.

For now, we can find a way to use `ADD` without modifying the structure of bundle.tar.gz, and add caching for the npm dependencies afterwards. Another idea is to:

1. ADD the bundle to `/__mup_bundle`
2. In a run command, symlink `/built_app` to `/__mup_bundle/bundle` and install npm dependencies

Docker might be able to cache the ADD step since the tar file isn't being modified, depending on how much metadata is kept when copying it to the server.

**Comment by SimonSimCity** [comment]
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache says:

> * For the ADD and COPY instructions, the contents of the file(s) in the image are examined and a checksum is calculated for each file. _The last-modified and last-accessed times of the file(s) are not considered in these checksums._ During the cache lookup, the checksum is compared against the checksum in the existing images. If anything has changed in the file(s), such as the contents and metadata, then the cache is invalidated.
> * Aside from the ADD and COPY commands, cache checking does not look at the files in the container to determine a cache match. _For example, when processing a `RUN apt-get -y update` command the files updated in the container are not examined to determine if a cache hit exists. In that case just the command string itself is used to find a match._

So re-uploading a already built version of your meteor app will not re-create the layer. I think that is what you were referring to, right?

In case the data changes, a rebuild of the system-stuff is required anyways, excepted for if you could take the users app data separately from his npm packages ... In this case you'd have to change the content of the `tar.gz` file, which I guess is not an option since we want to allow builds outside of `mup`.

**Comment by zodern** [comment]
This has been added to Mup 1.5: https://github.com/zodern/meteor-up/blob/8b7213330e272b7241da1b1d79b5c32135de39dd/src/plugins/meteor/assets/prepare-bundle.sh#L37-L40.

Thanks @SimonSimCity for suggesting this.

**Comment by SimonSimCity** [comment]
I think it's good to note that these changes have been reverted. See the reason in the comment on the commit: https://github.com/zodern/meteor-up/commit/3d8ea23165767e7f122294bdab46eb2d7971880c#diff-df0f0089255b343eb358fa7c27a482c1
