### ISSUE TITLE
MUP dead again?

### ISSUE THREAD

**Issue by stefanve** [zodern/meteor-up#1074]
Well, I am removing my backing.
I think the least someone who asks and recieves backing for a project could do when they abandon it is to mark it as dead so we get a chance to make choices _before_ we realize our processes has stopped working.

**Comment by zodern** [comment]
Meteor Up is not dead. Progress has slowed, but I have been working on a couple improvements such as rolling deploys and handling failed deploys with swarm as I have time. My schedule will be changing in the near future so I will be able to spend more time on Meteor Up. I use Mup in production in a few projects and have many ideas and plans for it.

**Comment by x5engine** [comment]
So why don't have any updates about the failed broken SSL?? I have more than two production apps broken now because of SSL which used to be working for the last few years perfectly with my bought SSL certificate...

I don't  want the free letsencrypt SSL it never worked for me or anyone I know here...

I just want the deployment to work again as it used to be... If you have new feature make a new branch and keep the working master one stable please.
@zodern

Seriously I was going to post a rant issue here but saw this one, I have wasted a month just with the SSL certificate part here in pup!!! Docs not clear at about it too!
Thanks
