### ISSUE TITLE
Feature request: option for Node garbage collection settings

### ISSUE THREAD

**Issue by derwaldgeist** [zodern/meteor-up#124]
I have the problem that my Meteor app deployed on a t2.micro instance at AWS crashes after some weeks, due to memory overflow. I first thought that it would be caused by a memory leak, but in this thread I've learned that this can happen because Node's garbage collection is not fast enough:

https://forums.meteor.com/t/how-to-find-memory-leaks-in-a-meteor-app/19008

User alveoli recommended to patch the Node config:

https://forums.meteor.com/t/how-to-find-memory-leaks-in-a-meteor-app/19008/16

and later reported that he did not have any memory issues since. However, I'm a bit hesitant about forking mupx for this, as I would prefer to stick to the standard mupx implementation.

So I'd like to suggest to add an option to configure the node settings if required. This would be great!

BTW: I am slightly confused about which version of mup(x) should actually be used for production purposes. In the repos, it seems to be mupx (and I am using this ATM). But if I enter an issue there, I always get redirected here. :-)

**Comment by madushan1000** [comment]
Both mup and mupx uses `meteorhacks/meteord` ad the docker image. You can modify that to your need and push it to the registry and specify `meteor.dockerImage` section to use that.
Changing node options from the mup/mupx side might be a lot complex than it seems.

**Comment by MasterJames** [comment]
Hi all yes I've been hopeful we switch since meteor 1.3 release to this kadirahq version officially. I think that maybe there's a need for documentation here still. Otherwise it seems people questions and PRs would go unanswered and the hope is to get everybody using or trying and reporting issues on this version so it's more robust. Simply the old versions are running into to many problems with new changes going on so it's really important to keep routing people to where the development team is available on this version.
I may not be continuing a watch status on the old version soon so people will get fustrated without a quick reminder about this port.
Still mupx seems to be working okay but so many great new features here can solve lots of remaining problems and the only way forward.
Let's try to get more officially switched on here if we are not already or there's a timeline when to plan for that would be good to know, thanks.

This problem is related to the build server only flag in a recent issue (merged PR) where there currently isn't a way to do this but should be for another reason now.

**Comment by MasterJames** [comment]
https://github.com/kadirahq/meteor-up/pull/120
You could add a similar PR I suppose but a better solution would be appreciated.
Maybe this is a good place as any to discuss what the solution could be.
How will it be best to put these in the settings file? 
How will it be best to have a template example customizable docker container that includes them on the command line? 
I wondered maybe there is or needs to be environment variables for these node flags too and so maybe we should be asking meteor forum about adding it to meteor first?

**Comment by MasterJames** [comment]
Looking for main.js ? 
https://github.com/meteorhacks/meteord/blob/master/base/scripts/run_app.sh#L44
You could put something there no?

Digging around for leads I saw this about a 'start' value in package.json ? With environment arguments getting to node but like he said it's harder then you'd think maybe the wrong direction as that would go in the meteord image or something? But the idea is you'd set the environment variable to get the options/arguments to node.
http://stackoverflow.com/a/30272349/4928388

**Comment by msj121** [comment]
@madushan1000 @derwaldgeist What was the end solution to doing this with kadirahq and not meteor hacks (as it states not to use it for Meteor 1.4)? Is there a way to put the command in mup.js? Or editing a mup file?

**Comment by derwaldgeist** [comment]
@msj121 I did not find a solution for this yet, as I did not want to fork mupx for this.
