### ISSUE TITLE
mup setup error on windows

### ISSUE THREAD

**Issue by willygwu** [zodern/meteor-up#218]
If I run the following command in cmd on windows
c:\Meteor\myproject.deploy>c:\Users\me\AppData\Roaming\npm\mup setup

then, this error message shows. can somebody help?
I am just trying to deploy on my local pc, after that i am going to deploy to real window server

Started TaskList: Setup Docker
[192.168.xxx.xxx] - setup docker
Error connect ECONNREFUSED 192.168.xxx.xxx:22

my mup.js is

module.exports = {
  servers: {
    one: {
      host: '192.168.xxx.xxx',
      username: 'root',
      password: 'xxx'
      // pem:
      // password:
      // or leave blank for authenticate from ssh-agent
    }
  },

  meteor: {
    name: 'hippochat',
    path: '../hippochat',
    servers: {
      one: {}
    },
    buildOptions: {
      serverOnly: true,
      debug:true
    },
    env: {
      ROOT_URL: '192.168.xxx.xxx',
      MONGO_URL: 'mongodb://localhost/meteor'
    },

```
//dockerImage: 'kadirahq/meteord'
deployCheckWaitTime: 60
```

  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {}
    }
  }
};

**Comment by martinhbramwell** [comment]
It means that a secure shell connection like ...

```
ssh root@192.168.xxx.xxx
```

... that replies to the password prompt with 'xxx', **does not succeed**.

Since you are on Windows, you need to ensure that you can open a working secure shell connection, as root to that server, with Putty, I suppose.

UID/Pwd are possible with SSH servers but very strongly discouraged.  You really should use SSH keys.

I do not use `root`. I created a distinct user on the server that is enabled to do `mup` work -- exclusively.  I set the SSH daemon configuration to prohibit remote root logins and to prohibit password based logins.

If this is all new to you, trust me, your best bet is use `mup` from within an Ubuntu virtual machine, in your Windows machine.  I believe you will lose **a lot** of time trying to work through all the weirdness of Windows for this kind of work.

Alternatively, and much wiser: deploy from a continuous integration service like CircleCI or Travis.

In the next few days, I'll be posting details of an example project that deploys with `mup` from CircleCI.  You can read about the first stage of that in [Kickstarter gets Continuous Integration](https://talk.mantrajs.com/t/kickstarter-gets-continuous-integration/489).  Look for an article, "Kickstarter gets Continuous Deployment".

**Comment by willygwu** [comment]
thanks for your reply... Let me try one more time. I cannot succeed, better to go with Ubuntu

**Comment by martinhbramwell** [comment]
If you want to see my experimentations and failures as they happen : 

[MUP deploy entry point](https://github.com/yourse1f-yourorg/mmks/blob/ci_deploy/.deploy/ci_deploy.sh)

and 

[CircleCI Build Attempts](https://circleci.com/gh/yourse1f-yourorg/mmks)

**Comment by yrvlucero** [comment]
Were you able to solve this problem. I keep getting this error even if I am using ssh key. Can someone point me in the right direction in deploying meteor app to local host with SSL authentication?

**Comment by martinhbramwell** [comment]
No. Sorry, I did not.  I have given up on `mup`.  As you can see it has dozens and dozens of unresolved issues, and ignored PRs going back half a year.

**Comment by shadowcodex** [comment]
You are free to reopen this issue if this problem still persists. There have been a lot of improvements made since the end of this thread.

**Comment by ghost** [comment]
@martinhbramwell I am also getting the same error on Windows and Ubuntu, too. I am using Meteor 1.6
mup.js
```
module.exports = {
  servers: {
    one: {
      host: '192.168.1.104',
      username: 'gabriel',
      password: 'gabriel',
      opts: {
        port: 5555
      }
    }
  },

  app: {
    // TODO: change app name and path
    name: 'ReportApp',
    path: '../',

    servers: {
      one: {},
    },

    buildOptions: {
      serverOnly: true,
    },

    env: {
      ROOT_URL: 'http://reportapp.com',
      MONGO_URL: 'mongodb://localhost/meteor',
      MONGO_OPLOG_URL: 'mongodb://mongodb/local',
    },

    docker: {
      image: 'abernix/meteord:base',
    },
    enableUploadProgressBar: true
  },

  mongo: {
    version: '3.4.1',
    servers: {
      one: {}
    }
  },
};

**Comment by martinhbramwell** [comment]
@gabimoncha 
I no longer use Meteor.

**Comment by ghost** [comment]
@martinhbramwell why not? What are you using now? I am using it to learn JavaScript. Do you recommend other frameworks?
