### ISSUE TITLE
Exit with 0 even on failure

### ISSUE THREAD

**Issue by tuarrep** [zodern/meteor-up#320]
Hi all!

I'm using mup in a continuous delivery environment.
Sometimes `mup deploy` fails (wrong on my side) but but no failure is reported by my CD system.

It seems `mup deploy` exits with 0 even on failure. Is it for reasons or it can be edited to report the failure to the delivery system?

Log example:

``` bash
$ mup deploy
Building App Bundle Locally

Started TaskList: Pushing Meteor
[guy] - Pushing Meteor App Bundle to The Server
[guy] x Pushing Meteor App Bundle to The Server: FAILED
    No such file
(node:41) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: No such file
Creating cache deploy-demo/deployment...
node_modules/: found 17061 matching files          
Build succeeded
```

**Comment by auro** [comment]
Production quality meteor deployments? Where?

Several jenkins automated builds are failing now because of this return code mismatch.

Help guys, please!

**Comment by myktra** [comment]
I suspect this is a regression in 1.0.4.

I too observed the `UnhandledPromiseRejectionWarning` error, among several others (it seemed inconsistent).

Initially I noticed this in a Codeship environment. Since Codeship instantiates a new build environment each time you deploy, and I hadn't pinned an npm install of mup in my custom setup script, 1.0.4 wound up getting installed.

To troubleshoot I deployed again via my local workstation mup – which I happened to have an older version (1.0.3) – and everything worked just fine. I decided to try to upgrade locally to 1.0.4 and now I get the same issue outside of the Codeship environment.

Reverting back to mup 1.0.3 fixed things up and now it works both locally and through Codeship.

**Comment by goooseman** [comment]
anyway this is a dublicate. 
dev team said this is by design: https://github.com/kadirahq/meteor-up/issues/137

but maybe we can make a PR to make this configurable?

I'm using bitbucket pipelines CI and really don't like the idea of it telling "Build succeed", when it wa actually failed.

**Comment by auro** [comment]
Sadly we have abandoned MUP strategy, since it creates more problems than it can solve.

**Comment by goooseman** [comment]
@auro and what are you using now? (if it is not a secret, hah)

**Comment by auro** [comment]
Hi @goooseman, how are you?! Fine i hope ;)

There's no secret at all, we generate the bundles right on Jenkins, then send, uncompress and deploy it on preconfigured nodejs.

No more surprises or fucked up docker images to deal with.

**Comment by goooseman** [comment]
@auro cool, smth simple is always the best option 👍

**Comment by zodern** [comment]
I would accept a pull request that adds an env variable to change this behavior.

**Comment by fuatsengul** [comment]
Hope we see some updates on this, a fully CI compatible test-build-deploy stage support would be great!

**Comment by artgo** [comment]
+1 we do need the same

**Comment by zodern** [comment]
In 1.3.1, the error code will be 1 when a task list fails.
