### ISSUE TITLE
port is not honored

### ISSUE THREAD

**Issue by sirpy** [zodern/meteor-up#347]
when setting the env: { PORT: 81} the port it binds to is always 80 no matter what port i put there.

**Comment by adrianolsk** [comment]
~~Yes, I just got the same problem, had to stop nginx that was running on port 80 to be able to deploy my app, even after change port to 3000 on mup.js it still deploys using port 80~~

never mind I was setting meteor.port instead of meteor.env.PORT, now I got `0.0.0.0:3000->80/tcp` which is exactly what I wanted to be able to use nginx and point my domain to port 3000

**Comment by ivanthemeh** [comment]
@adrianolsk can you tell me how you fixed this? IM having an issue where if I set the port to port 80 it will connect but if I set it to anything else it refuses to connect.
