### ISSUE TITLE
I can't disable Mongo installing

### ISSUE THREAD

**Issue by mzygmunt** [zodern/meteor-up#37]
Hello,
Changing the option setupMongo from 1 to 0 does not affect the installation of Mongo. Despite it, Mongo is installed and configured on the server.

**Comment by arunoda** [comment]
@madushan1000 could you take a look at this. I think it seems like a bug.

**Comment by madushan1000** [comment]
Note the mup.js format is changed a bit.

```javascript
module.exports = {
  servers: {
    one: {
      host: '0.0.0.0',
      user: 'root'
    }
  },

  meteor: {
    name: 'app',
    path: './app',
    servers: {
      one: {}, two: {}, three: {}
    },
    env: {
      MONGO_URL: 'mongodb://localhost/meteor'
    },
  },

  mongo: {
    oplog: true,
    port: 27017,
    servers: {
      one: {},
    },
  },
  setupMongo: 1,
  deployCheckWaitTime: 20
};
```

**Comment by mnmtanish** [comment]
Can we do this without adding extra fields to `mup.js`? I guess we can check whether `module.exports.mongo` exists for that.

And the `deployCheckWaitTime` should go under `meteor` right?

**Comment by madushan1000** [comment]
We can check for `module.exports.mongo` but what if someone needs to turn off mongo setup temporarily, but keep their mongo settings?
I think having `deployCheckWaitTime` under `meteor` is a little confusing, that's why I moved it to the project scope. We can move it back if you think it doesn't make sense.
