### ISSUE TITLE
mup no fails

### ISSUE THREAD

**Issue by maryito** [zodern/meteor-up#370]
Please help does not work me desploy. I've tried it many times and nothing

Started TaskList: Setup Docker
[192.168.0.20] - setup docker
[192.168.0.20] - setup docker: SUCCESS

Started TaskList: Setup Meteor
[192.168.0.20] - Setup Environment

Started TaskList: Setup Mongo
[192.168.0.20] - setup environment
[192.168.0.20] x setup environment: FAILED
        
        -----------------------------------STDERR-----------------------------------
        sudo: sin tty presente y no hay programa askpass especificado
        sudo: sin tty presente y no hay programa askpass especificado
        -----------------------------------STDOUT-----------------------------------
        ----------------------------------------------------------------------------
[192.168.0.20] x Setup Environment: FAILED
        
        -----------------------------------STDERR-----------------------------------
        sudo: sin tty presente y no hay programa askpass especificado
        sudo: sin tty presente y no hay programa askpass especificado
        sudo: sin tty presente y no hay programa askpass especificado
        sudo: sin tty presente y no hay programa askpass especificado
        -----------------------------------STDOUT-----------------------------------
        ----------------------------------------------------------------------------

**Comment by raymondtm** [comment]
SSH based authentication with sudo

If your username is root or you're using AWS EC2, you don't need to follow these steps

Please ensure your key file (pem) is not protected by a passphrase. This setup process will require NOPASSWD access to sudo. (Since Meteor needs port 80, sudo access is required.)

Make sure you also add your ssh key to the /YOUR_USERNAME/.ssh/authorized_keys list.

You can add your user to the sudo group:

sudo adduser *username*  sudo
And you also need to add NOPASSWD to the sudoers file:

sudo visudo

# replace this line
%sudo  ALL=(ALL) ALL

# by this line
%sudo ALL=(ALL) NOPASSWD:ALL
When this process is not working you might encounter the following error:

'sudo: no tty present and no askpass program specified'

**Comment by zodern** [comment]
@maryito did you fix it?

**Comment by maryito** [comment]
yes
thank you very much

**Comment by erperejildo** [comment]
I did the same but stil having same issue. Not using ssh key

Edit: working now, I was doing this change on my local machine
