### ISSUE TITLE
Instructions about .deploy are confusing

### ISSUE THREAD

**Issue by reduxdj** [zodern/meteor-up#47]
I don't understand why i am to initialize my mup project inside a .deploy directory, I already have a meteor project. I'd like to try figure out how to build it with mup?

**Comment by madushan1000** [comment]
create a `.deploy` folder at the root of your meteor project directory(meteor doesn't read from hidden folders), Or create it somewhere else outside your meteor project tree. Otherwise `mup.js` will create issues because meteor try to read it. This is just a temporary precaution. We will fix it eventually.

Additionally, a mup project only have your deploy configurations(mup.js and settings.json). Don't confuse it with meteor project (Which is your javascript/etc... code)
