### ISSUE TITLE
Warn when using mup instead of mup.cmd on Windows

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#487]

**Comment by gjr-qm** [comment]
I think this solution will not work because Windows tries to run mup.js (the mup config file). So the warning has to be in the mup.js file. I think that is not the most clean solution.

Maybe change mup.js to mupconfig.js?

So in mup you can check if mup.js exists. If not then check mupconfig.js. Changing the name of the config file will take care of the mup command not being intercepted.

**Comment by gjr-qm** [comment]
@zodern: If you like the idea I could implement it in a PR...

**Comment by zodern** [comment]
It would work when running `mup init`. It's not perfect, but better than nothing.

> Maybe change mup.js to mupconfig.js?

I have been considering that.

Also, this seems to only happen in Command Prompt. In Windows 10 Creator's update, Power Shell will become the default shell.

**Comment by gjr-qm** [comment]
I think a warning is a no-go. Making the mupconfig.js optional would solve current problems for Windows users. But it's your call @zodern. If you want me to implement it (optional), just let me know.

**Comment by gjr-qm** [comment]
Another option is updating the documentation for now with a warning for Windows users to use mup.cmd  instead of mup.

**Comment by shadowcodex** [comment]
Merged: https://github.com/zodern/meteor-up/pull/516
