### ISSUE TITLE
No gh-pages branch

### ISSUE THREAD

**Issue by shadowcodex** [zodern/meteor-up#497]
@zodern can you create a gh-pages branch so that I may pull request into it? Go ahead and create it and then delete the contents of that branch.

I am ready to submit a pull request from my branch here: https://github.com/shadowcodex/meteor-up/tree/gh-pages

Demo Site: https://shadowcodex.github.io/meteor-up/

Enjoy,
ShadowCodex

**Comment by shadowcodex** [comment]
Screen cap of site:

![meteor-up-site](https://cloud.githubusercontent.com/assets/1348053/23437273/1908b2a4-fdd3-11e6-84f0-06b86d44fe90.png)

**Comment by zodern** [comment]
This is a great start!

Please move everything in your `gh-pages` branch to the `/docs` folder in the `master` branch.

**Comment by shadowcodex** [comment]
I'll do that after we finish and merge the current PR.

**Comment by shadowcodex** [comment]
Do you want me to just push this as a commit instead of a PR?

**Comment by zodern** [comment]
A commit is fine. I would like to discuss some of the content first.

- One thing that concerns me is is mup really the fastest way to deploy meteor apps? Compared to other options of deploying to a vps, it probably is. But I don't think it is compared to using a PaaS.
- Please remove the x from the "Heads up!" box
- You can also remove the navbar since it only has the one link.

> You are free to deploy to anywhere over ssh. You are not tied to Galaxy.

I would prefer it to be more broad, that you are not tied to a specific platform or infrastructure as a service.

**Comment by shadowcodex** [comment]
Alright, good changes.

**Comment by shadowcodex** [comment]
Pull request active: https://github.com/zodern/meteor-up/pull/517
