### ISSUE TITLE
Difference from arunoda/meteor-up

### ISSUE THREAD

**Issue by SantoshSrinivas79** [zodern/meteor-up#53]
Hi Guys, What the difference of this from [arunoda/meteor-up: Production Quality Meteor Deployments](https://github.com/arunoda/meteor-up)?

Can you please put some notes to help users who don't actively track the developments?

Thank you.

**Comment by madushan1000** [comment]
This is the same thing, Just a refatored/moduler version. And this is still in development.

**Comment by MasterJames** [comment]
It's more like mupx then mup I would expect right?

**Comment by madushan1000** [comment]
Yeah, We are planning port all of the mupx features to this version. We are mostly done. Only a few thing  left. Community help is verry well appriciated :)

**Comment by MasterJames** [comment]
I did this somewhat crazy experimental PR for MUPX that adds Mongo Restore and Dump.
https://github.com/arunoda/meteor-up/pull/736
Maybe you can try to merge some of that yourself, or let me know when it's safe to try rebuilding it into this new version. I'm basically waiting for a notice in the README redirecting people to this one when it's ready.

**Comment by carlosbaraza** [comment]
Hi, would it be possible to update the README at arunoda/meteor-up indicating that the development is discontinued in that repo?

I spent the past weekend working on the integration of Let's Encrypt in that repo because I did not know that this repo existed (arunoda/meteor-up#873 and meteorhacks/mup-frontend-server#10).

Thanks for the refactoring and the addition of tests.

**Comment by madushan1000** [comment]
@MasterJames You can send a PR to this repo. It's currently stable enough for anyone to develop against. No major design changes will happen (hopefully).
@carlosbaraza Sorry for the inconvenience. We started developing this repo specifically because It was very hard to accept PR's into old repo due to the lack of integration testing. We updated the README of the old repo. Thank you.

**Comment by carlosbaraza** [comment]
Hi @madushan1000, thank you for updating the README. At least now new developers could know the actual state and place to contribute.

**Comment by MasterJames** [comment]
Okay thanks good to know.
I'm thinking you could update the Arunoda development branch mupx's Readme too.
https://github.com/arunoda/meteor-up/tree/mupx

**Comment by ghost** [comment]
So this mup is the correct and current mup to be using?

**Comment by madushan1000** [comment]
No, this is the development version. For production, Use mupx.
