### ISSUE TITLE
Set mup in order to access meteor in port 3009 (or any port)

### ISSUE THREAD

**Issue by rbrugnollo** [zodern/meteor-up#590]
Hey guys, I'm trying to figure out how to set up my mup.js file in order to access meteor from a different port other than 80.

So, I tried many different setups, for me the one that makes more sense is:

```
{
...
env: {
PORT: 80,
ROOT_URL: 'http://test.mymeteorapp.com',
MONGO_URL: 'mongodb://localhost/mymeteorapp',
},
docker: {
image: 'abernix/meteord:base',
imagePort: 3009,
},
deployCheckPort: 80,
...
}
```

Everything works but when it gets to "Verifying Deployment" step it fails.

Any ideas on how to get this working?

Thanks!

**Comment by zodern** [comment]
`abernix/meteord:base` requires `imagePort` to be `80` for it to work. You can use https://github.com/abernix/spaceglue instead, which uses `3000`.

**Comment by zodern** [comment]
With mup 1.2.9, it should work with almost any number for `imagePort`. If you want to change what port the app is accessed on, you want to change `env.PORT` instead.

**Comment by layik** [comment]
@zodern could you please help me with this too. The SSL error if I set `meteor.env.PORT` in mup.js is fine and understandable, but when using an nginx proxy container, how could both containers listen on :80? 
Right now we have a bad gateways because the nginx container is not able to query the `meteord` as the proxy value is set to ROOT_URL:80?

Thank you very much.
