### ISSUE TITLE
Site is down while finishing deploy

### ISSUE THREAD

**Issue by SachaG** [zodern/meteor-up#604]
I've noticed that whenever I deploy, my site goes down for a few seconds at the end of the process. I can live with this, but I was just wondering if this was the expected behavior, or if this is a bug?

**Comment by zodern** [comment]
It will be down while running the task list `Start Meteor`. I am looking into ways to reduce it.

**Comment by zodern** [comment]
This has been improved in 1.3, 1.4, and 1.4.5.

In 1.3, installing the app's npm dependencies was moved from starting the app to a new task called `Prepare Bundle`, which builds a new docker image containing the app's bundle and npm dependencies. One benefit is this allows the app to start much faster.

In 1.4, `Verifying Deployment` was improved to stop and revert the app early if it spends a large amount of time restarting due to the app repeatedly crashing. If the deployment failed, it is reverted about 30 seconds after starting the app instead of waiting the full time in `deployCheckWaitTime` + 15 seconds.

The app is normally stopped during Prepare Bundle to avoid running out of memory when building the docker image. 1.4.5 adds the option `app.docker.stopAppDuringPrepareBundle` which disables that when set to false. When disabled, the downtime is only the amount of time it takes to create the docker container and for the app to start, which is usually a few seconds.
