### ISSUE TITLE
PORT can not be set when using ssl.autogenerate

### ISSUE THREAD

**Issue by bduff9** [zodern/meteor-up#671]
I have one app deployed on my server (using HTTP) and am trying to deploy a second (hopefully using SSL).  I tried the autogenerate but it gives me the error "PORT can not be set when using ssl.autogenerate".  I am unsure how to set up letsencrypt on my server for this app.

I have nginx sitting in front of my apps, and that uses SSL, but certbot fails when I run it on my server and mup won't let me specify a port when deploying.  How can I proceed?

**Comment by zodern** [comment]
You could try using the [reverse proxy](https://github.com/zodern/meteor-up#reverse-proxy). You could configure it for the one app using Let's encrypt, and instead of changing the app's port, change the [proxy's port](https://github.com/zodern/meteor-up#advance-configuration). Contrary to what the docs currently say, it is only used for apps that have `proxy.domains` set.
