### ISSUE TITLE
trouble migrating from mup to mupx on ubuntu, cannot deploy

### ISSUE THREAD

**Issue by chrisco23** [zodern/meteor-up#69]
Hi,

Sorry for a duplicate post but I posted yesterday accidentally to the arunoda/mup when I really meant to post here.  So here is what I posted:

I've been running an app at alpha stage on a Digital Ocean droplet for a long time, and deploying with mup. I hadn't worked on it in some time and I read that mup is no longer maintained, so I tried to use mupx.

On this server I run several small sites, with nginx. I had been using the nginx proxy method for my meteor app with mup to deploy.

I really do not want to purchase and maintain a whole new droplet just for this app.

Do I understand correctly that mupx is trying to install its own nginx in a docker container? I'm new to docker.

I googled and found some similar problems but no solutions. A lot of threads I read were discussing SSL, which I'm not even attempting for this app (yet).

In mup.json (with mup) I had port set to 3000. with the mupx and the new mup.json, I tried both port 80 (as in the default file). I'm trying 3000 now and I get this:

-----------------------------------STDERR-----------------------------------
Failed to remove container (myappname-frontend): Error response from daemon: No such container: myappname-frontend
docker: Error response from daemon: failed to create endpoint myappname on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:3000: bind: address already in use.
-----------------------------------STDOUT-----------------------------------
m-staging-etfinvest-com
base: Pulling from meteorhacks/meteord
518dc1482465: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
537c534356b6: Already exists
b65a0e1e554b: Already exists
a3ed95caeb02: Already exists
a3ed95caeb02: Already exists
Digest: sha256:b5a4f6efa98e4070792ed36d33b14385a28e6ceda691a492ee5b9f2431b1515a
Status: Image is up to date for meteorhacks/meteord:base

**Comment by madushan1000** [comment]
One clarification, Old mup/mupx is still god for production use (in fact it's recommended since this version is not yet fully ready). We are just not doing any new developments/feature adding to it. 

As for the issue, Mup does not support using Nginx as a proxy (yet). If you want to use it as a proxy, You will have to install and configure Nginx manually (here is a doc on how to do that https://github.com/arunoda/meteor-up/wiki/Using-Meteor-Up-with-NginX-vhosts). What mup uses Nginx for is to provide SSL support (Which is a separate use case). 
Other than that, I can see you have something running on your port 3000. Kill it or change to port  something other than 3000 before you deploy.

**Comment by chrisco23** [comment]
Thanks.  I already have the nginx proxy vhost set up.  Could that be what's
interfering with mupx?

Given that setup do you think i need to revert to mup?

**Comment by madushan1000** [comment]
It could be if that setup is what's binding to the port 3000. Changing the port should work.

**Comment by madushan1000** [comment]
I hope this is fixed, Reopen if not.

**Comment by chrisco23** [comment]
sorry I only now saw this.  Yes I don't even remember the details but I'm no longer having the issue, thanks.
