### ISSUE TITLE
Set COMPAT_VERSION for IOS & Android

### ISSUE THREAD

**Issue by thijssmudde** [zodern/meteor-up#730]
**How is it possible to set METEOR_CORDOVA_COMPAT_VERSION_IOS & METEOR_CORDOVA_COMPAT_VERSION_ANDROID with Meteor Up?**

Its this file Im talking about. How to force values in this, particularly these two values
https://myroutes.io/__cordova/manifest.json

**Comment by tekstop** [comment]
any hints on this?

**Comment by johan-insthink** [comment]
@fullhdpixel Did you by any chance to solve this?

**Comment by johan-insthink** [comment]
In case anyone is having the same issue — what I ended up doing was passing these ENV-variables when running `mup deploy` since that is when the build process starts.

**For example:**

`METEOR_CORDOVA_COMPAT_VERSION_IOS=IOS_HASH mup deploy` 

However, it would be nice to be able to set env-variables in the build process using the `mup.js`-conf file.
