### ISSUE TITLE
npm install before mup deploy?

### ISSUE THREAD

**Issue by edemaine** [zodern/meteor-up#765]
I've been burned a few times by following a pattern of `git pull; mup deploy`, which grabs changes from development on another machine, including changes to NPM dependencies in `package.json`.  But we need to `meteor npm install` before `meteor build`, so the NPM dependencies don't get updated:

> Any npm dependencies must be installed before issuing the meteor build command to be included in the bundle. [[Custom deployment](https://guide.meteor.com/deployment.html#custom-deployment)]

Could we add `meteor npm install` as part of the build process?  I can't imagine this being a bad thing, and it would have saved me from messing up my server a few times.

**Comment by zodern** [comment]
This is one reason hooks were added to mup. You can add one in your config to run `npm install`. For example:
```js
hooks: {
    'pre.deploy': {
      localCommand: 'meteor npm install'
    }
}
```

**Comment by edemaine** [comment]
Cool, thanks, that's a good fix.  I still feel like this could be part of the Meteor build process, to save people from themselves...  Would you object to a PR to this effect?  Or do you think there are circumstances where we shouldn't run `meteor npm install` before `meteor build`?

**Comment by zodern** [comment]
I think it is better to have the user handle installing dependencies because:
- there are a variety of package managers that different apps use (npm, yarn, pnpm, etc.)
- In many situations, the dependencies are already installed, such as in ci where they are installed before running tests (Meteor should exclude the dev dependencies when creating the bundle), and it would unnecessarily slow down the deploy.
