### ISSUE TITLE
Only build Docker image?

### ISSUE THREAD

**Issue by houshuang** [zodern/meteor-up#771]
I'm not sure how complicated the logic for building Docker images with MUP is, but I was wondering if it was possible to ask mup to only build an image and store it locally - if we wanted to deploy it to the server ourselves?

**Comment by zodern** [comment]
With mup 1.3, depending on the docker image in the config, it might build one on the server using [this dockerfile](https://github.com/zodern/meteor-up/blob/master/src/plugins/meteor/assets/prepare-bundle.sh#L28). 
Otherwise, it doesn't build a image and instead mounts the app in a volume.

You could create a plugin that runs the command `meteor.build` to build the app, and then creates a docker image.
