### ISSUE TITLE
This project still alive?

### ISSUE THREAD

**Issue by stefanve** [zodern/meteor-up#848]
I notice that http://meteor-up.com/ is not running and the readme refers that site for documentation. There is also many open issues and many of them to the same problem with the outdated default docker image, but documentation does not mention it. I'm asking because I do not want to sit with yet another outdated MUP variation... 

I like MUP and I thank everyone involved, but if it is being abandoned, I'd like to know :)

**Comment by zodern** [comment]
The past month I haven't had much time to work on Meteor Up, but I am planning to later this week.

The website is working for me right now. The docker images are documented at http://meteor-up.com/docs.html#meteor-support, though the docs do need to be reorganized and improved since it seems many users have difficulty finding the information they need.
