### ISSUE TITLE
Pushing a docker image built by meteor-up to a registry

### ISSUE THREAD

**Issue by znat** [zodern/meteor-up#866]
Is it possible, instead of deploying, to push a Docker image to a registry?

**Comment by zodern** [comment]
It is possible to create plugins that deploy the app, for example, [mup-aws-beanstalk](https://github.com/zodern/mup-aws-beanstalk). It should be possible to create a plugin that pushes a docker image instead of deploying.

**Comment by zodern** [comment]
This will be possible with mup 1.5.2. You can configure mup to use a [private docker registry](http://meteor-up.com/docs.html#private-docker-registry), set the `app.docker.runPrepareBundleLocally` option, and then run `mup push` instead of `mup deploy`. This will build the app, build the docker image, and then push it to the registry.

**Comment by CyberCyclone** [comment]
I don't understand how this works. I'm running 1.5.3, and building and pushing a Docker image to the registry doesn't seem to work.

Doing a search in this Git for 'runPrepareBundleLocally' returns a single result referencing here; it doesn't seem to be in any code. ```mup push``` is an invalid command. The docs have nothing about a 'push' command.
