### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by zodern** [zodern/meteor-up#902]
Over the past year, there has been a lot of progress in Meteor Up. Many pain points have been fixed, plugins are now supported, and there is a reverse proxy that supports Let's Encrypt.

However, there is still much more that needs to be done. To help speed up development, I would like to get help from the community. Here are some ways you can assist:

**Docs**

The docs need improvement. It would be greatly appreciated if someone could review the docs and make a list of sections that need to be expanded or updated. The docs also need to be reorganized to make it easier to find a certain topic.

**Code**

I could use help with implementing new features. GitHub projects are used to plan what will be in a release. You can view the projects [here](https://github.com/zodern/meteor-up/projects). There also is a [road map](https://github.com/zodern/meteor-up/blob/master/ROADMAP.md) available. If you have any questions, use a GitHub issue or join the Gitter chat room.

The remaining items in the 1.4 project are mostly smaller changes that will help prevent problems. 1.5 has larger features focusing on load balancing and zero downtime deploys.

**Beta Testing**

Due to the wide variety of server setups and types of apps deployed with Meteor Up, new features occasionally break deploying an app for a subset of users. To help find bugs before a new version of mup is released, I have been releasing beta versions. Subscribe to the gitter chat room or watch for new pull requests to learn when a new beta is available, and please try it.

If you have some time and motivation, I would greatly appreciate any help.

**Comment by ninjaPixel** [comment]
Hey, @zodern! I'd love to help with this project. I've made a couple of minor pull requests to the docs (https://github.com/zodern/meteor-up/pull/1024 and https://github.com/zodern/meteor-up/pull/1025) and the automated build tests fail for both of them.

It's the `node tests/validate-docs.js` test which fails. This test passes for me, locally. 

Since I've just updated the docs, I'm assuming that I haven't actually broken anything and it is something peculiar to the continuous integration environment. Does this sound likely to you? Let me know if you need any more details.
