### ISSUE TITLE
Deploys fails on windows but works well on Mac

### ISSUE THREAD

**Issue by mediamana** [zodern/meteor-up#932]
Mup version : 1.4.4
Meteor version : 1.6.1.1

I have a project that deploys well on Mac but fails on Windows.

After some digging i've identified that the problem is related to windows path separator inside tarball.

At first i thought it was related to npm bug as stated in  . So i updated our project to meteor 1.6.1.1 but the problem is still there.

Then i realized that mup is doing the tarball itself. I then tried to do the tarball with meteor and deploy it with mup using option --cached-build. Doing so it deploys well.

I haven't digged more about this but i wonder what's the point about running meteor build with --directory option, then doing tarball yourself instead of just asking meteor to do the tarball directly ?

**Comment by zodern** [comment]
This is a bug in node-tar: https://github.com/npm/node-tar/pull/171.

> I haven't digged more about this but i wonder what's the point about running meteor build with --directory option, then doing tarball yourself instead of just asking meteor to do the tarball directly ?

The `meteor.build` command can be used by other plugins. For example, the mup-aws-beanstalk plugin [runs it](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/command-handlers.js#L134), adds files to the bundle, and then creates a zip file since aws beanstalk doesn't support tar files.

**Comment by zodern** [comment]
I published a beta version of mup (`1.4.5-beta1`) which is using a forked version of tar that has the fix for this. You can try it by running `npm i -g mup@next`.

**Comment by mediamana** [comment]
Thank you for the quick fix, i can confirm it is working on my project.

Best regards
