### ISSUE TITLE
multi server deployment is slower than mup 1.3.7

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#958]
I recently updated mup from 1.3.7 to the latest and I noticed that the meteor bundle is now dockerized on each server individually. With 1.3.7, the meteor docker image is built locally before being sent to each server. This makes deployment to multiple servers much slower. Is there a reason for doing this or my assumptions are wrong here?

**Comment by zodern** [comment]
What docker image did you use with Mup 1.3.7?

**Comment by WayneUong** [comment]
The `abernix/meteord` one. I tried your `zodern/meteor-docker` but it does feel a bit slower.

**Comment by zodern** [comment]
Prepare Bundle started being enabled by default for `zodern/meteor-docker` in Mup 1.4, which could have made deployments slower. There shouldn't be a large difference between 1.3.7 and 1.4.5 when using `abernix/meteord`.

Starting in Mup 1.3, mup builds a docker image on the server during Prepare Bundle. It does slow down deploys, but makes them much more reliable and easier to troubleshoot. It also greatly speeds up starting the app. In mup 1.4.5, there is a new option [`app.docker.stopAppDuringPrepareBundle`](http://meteor-up.com/docs#everything-configured), which when set to `false` reduces the downtime to the amount of time it takes the app to start.

For Mup 1.5, I am looking into caching the app's npm dependencies, which will make deployments much faster when the dependencies haven't changed since the last deployment.

**Comment by x5engine** [comment]
very nice @zodern but my app bundle is taking so much time! like 30 to 30 minutes wtf seriously?

**Comment by zodern** [comment]
In Mup 1.5 there are two more optimizations:
- When enabling the `app.docker.useBuildKit` option in the config, Prepare Bundle will be much faster
- If you deploy to multiple servers, you can use a [private docker registry](https://github.com/zodern/meteor-up/blob/c8251213b05dd166bb7222eec0f3f6a66835edf3/docs/docs.md#private-docker-registry). When it is enabled, uploading the bundle and running Prepare Bundle will only be done on one server instead of all of them.

If it is still too slow, you can disable Prepare Bundle with the `app.docker.prepareBundle` option.
