### ISSUE TITLE
Be Advised before you upgrade to meteor 1.7 and deploy!

### ISSUE THREAD

**Issue by x5engine** [zodern/meteor-up#963]
This is a Serious issue that might affect your deployment but I am not sure how you can run the current fix https://github.com/meteor/meteor/issues/9871#issuecomment-392897692

From mongo shell before you update you need to run
```js

db.adminCommand( { setFeatureCompatibilityVersion: "3.4" } )

```
Maybe using hooks?

Any suggestions?

**Comment by zodern** [comment]
The Meteor issue is from Meteor 1.7 tool using a newer version of MongoDB than the version that stored the data.

This doesn't affect Meteor Up  since you have full control over what version of MongoDB is used (by `mongo.version` in the config), and when the version changes. When changing `mongo.version`, make sure to follow [these instructions](http://meteor-up.com/docs#change-mongodb-version) to avoid problems.
